name: samyati
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  health: ^8.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  firebase_core: ^2.31.0
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^25.2.5
  firebase_auth: ^4.19.6
  awesome_dialog: ^3.2.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  simple_gradient_text: ^1.3.0
  carousel_slider: ^4.2.1
  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.3
  lottie: ^3.1.2
  syncfusion_flutter_datepicker: ^25.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/